### ISSUE TITLE
Error when using 'networks' configuration option in docker-compose v2

### ISSUE THREAD

**Issue by ksketo** [docker/dockercloud-haproxy#36]
On Mac OS X, this is my docker-compose (v2) file:

```yaml
version: "2"

services:
  lb:
    image: dockercloud/haproxy:1.2.1
    depends_on:
      - web
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 80:80
    networks:
      - lb-tier

  web:
    image: dockercloud/hello-world
    networks:
      - lb-tier

networks:
  lb-tier:
```

When I am trying to start the containers, the `lb` container, directly goes in exit status. Docker logs gives me the following:

```
INFO:haproxy:dockercloud/haproxy 1.2.1 is running outside Docker Cloud
INFO:haproxy:New link mode, loading HAProxy definition through docker api
INFO:haproxy:dockercloud/haproxy PID: 1
INFO:haproxy:==========BEGIN==========
INFO:haproxy:Initial start
Traceback (most recent call last):
  File "/usr/local/bin/dockercloud-haproxy", line 9, in <module>
    load_entry_point('dockercloud-haproxy==1.2.1', 'console_scripts', 'dockercloud-haproxy')()
  File "/usr/local/lib/python2.7/dist-packages/haproxy/main.py", line 43, in main
    run_haproxy("Initial start")
  File "/usr/local/lib/python2.7/dist-packages/haproxy/haproxycfg.py", line 24, in run_haproxy
    haproxy = Haproxy(config.LINK_MODE, msg)
  File "/usr/local/lib/python2.7/dist-packages/haproxy/haproxycfg.py", line 46, in __init__
    self.specs = self._initialize(self.link_mode)
  File "/usr/local/lib/python2.7/dist-packages/haproxy/haproxycfg.py", line 54, in _initialize
    links = Haproxy._init_new_links()
  File "/usr/local/lib/python2.7/dist-packages/haproxy/haproxycfg.py", line 82, in _init_new_links
    links, Haproxy.cls_linked_services = NewLinkHelper.get_new_links(docker, haproxy_container)
  File "/usr/local/lib/python2.7/dist-packages/haproxy/helper/new_link_helper.py", line 13, in get_new_links
    linked_compose_services = _get_linked_compose_services(networks, project)
  File "/usr/local/lib/python2.7/dist-packages/haproxy/helper/new_link_helper.py", line 79, in _get_linked_compose_services
    haproxy_links.extend(network.get("Links", []))
TypeError: 'NoneType' object is not iterable
```

However, if I use `links: -web` instead, the containers are linked.

**Comment by tifayuki** [comment]
@kencochrane 

`depends_on` only defines the start order of the services in the compose file. But `dockercloud/haproxy` reads `links` property to decided if the service will be balanced or not. You have to explicitly set `links` to make it work.

And the `NoneType` error is fixed in version `1.3`
