### ISSUE TITLE
After running for weeks, it raises RuntimeError: cannot join thread before it is started

### ISSUE THREAD

**Issue by peterlauri** [docker/dockercloud-haproxy#60]
I'm using this in a Stack, and suddenly after being up for weeks, it just raises and exception and dies. Does not restart. This is a low traffic web site. There are nothing else in the logs.

```
[lb-1]2016-05-13T01:34:31.926027191Z Traceback (most recent call last): 
[lb-1]2016-05-13T01:34:31.927063846Z   File "/usr/bin/dockercloud-haproxy", line 9, in <module> 
[lb-1]2016-05-13T01:34:31.929084513Z     load_entry_point('dockercloud-haproxy==1.3', 'console_scripts', 'dockercloud-haproxy')() 
[lb-1]2016-05-13T01:34:31.929103843Z   File "/usr/lib/python2.7/site-packages/haproxy/main.py", line 41, in main 
[lb-1]2016-05-13T01:34:31.929151507Z     listen_dockercloud_events() 
[lb-1]2016-05-13T01:34:31.929638324Z   File "/usr/lib/python2.7/site-packages/haproxy/eventhandler.py", line 60, in listen_dockercloud_events 
[lb-1]2016-05-13T01:34:31.930650973Z     events.run_forever() 
[lb-1]2016-05-13T01:34:31.930666543Z   File "/usr/lib/python2.7/site-packages/dockercloud/api/events.py", line 42, in run_forever 
[lb-1]2016-05-13T01:34:31.930711053Z     ws.run_forever(ping_interval=5, ping_timeout=5, *args, **kwargs) 
[lb-1]2016-05-13T01:34:31.934331712Z   File "/usr/lib/python2.7/site-packages/websocket/_app.py", line 206, in run_forever 
[lb-1]2016-05-13T01:34:31.934398989Z     thread.join() 
[lb-1]2016-05-13T01:34:31.939365659Z   File "/usr/lib/python2.7/threading.py", line 929, in join 
[lb-1]2016-05-13T01:34:31.939567346Z     raise RuntimeError("cannot join thread before it is started") 
[lb-1]2016-05-13T01:34:31.951178144Z RuntimeError: cannot join thread before it is started
```

**Comment by tifayuki** [comment]
@peterlauri 
This is an issue in the websocket-client package, and it has been fixed in the latest version of dockercloud/haproxy

Thank you
